### ISSUE TITLE
docker-compose.ymlを編集

### ISSUE THREAD

**Issue by yuki10000** [LearningEngineeringLaboratory/kbfira_setup#7]
### やること
- `docker-compose.yml`のmysqlのバージョンを修正
    - `image: mysql:latest`の部分を`image: mysql:8.0.36`に書き換え

**Comment by yuki10000** [comment]
- mysqlのバージョンを書き直した後、以下のコマンドを打って、dockerをリビルド
```
docker-compose down
docker-compose build
docker-compose up -d
```
- docker desktopにサインインした状態だとbuildがうまく動作しないというエラーが発生した。

> Building 1.9s (3/3) FINISHED                                                                                                                        docker:default
      => [nginx internal] load build definition from Dockerfile                                                                                                        0.0s
      => => transferring dockerfile: 869B                                                                                                                              0.0s 
      => ERROR [nginx internal] load metadata for docker.io/ajoergensen/nginx-php-fpm:8.2                                                                              1.8s 
      => [nginx auth] ajoergensen/nginx-php-fpm:pull token for registry-1.docker.io                                                                                    0.0s
     ------
      > [nginx internal] load metadata for docker.io/ajoergensen/nginx-php-fpm:8.2:
     ------
     failed to solve: ajoergensen/nginx-php-fpm:8.2: failed to resolve source metadata for docker.io/ajoergensen/nginx-php-fpm:8.2: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://auth.docker.io/token?scope=repository%3Aajoergensen%2Fnginx-php-fpm%3Apull&service=registry.docker.io: 401 Unauthorized          
     [+] Running 1/1
      ✘ mysql Error Head "https://registry-1.docker.io/v2/library/mysql/manifests/8.0.36": unauthorized: incorrect username or password                                1.4s 
     Error response from daemon: Head "https://registry-1.docker.io/v2/library/mysql/manifests/8.0.36": unauthorized: incorrect username or password

**Comment by yuki10000** [comment]
Live Serverを立ち上げると、[kit-buildの初期画面](http://localhost:8081/kbfira_docs/index.php/kitbuild/)と[Concept Mapの初期画面](http://localhost:8081/kbfira_docs/index.php/cmap)が無限リロードされるという問題があったが、mysqlを更新して再度立ち上げると直った...

**Comment by koutyai** [comment]
docker desktopにサインインした状態だとbuildがうまく動作しないというエラーについて，docker desktop上でのサインインとVSCode上でのサインインは別なので，両方ともサインインした状態か，していない状態に揃える必要があるとのこと．

**Comment by koutyai** [comment]
その後，KBシステム上でサインインできなくなった．docker psしたらMySQLのコンテナが立ち上がっていなかったのでログを見てみたところ，バージョン間の互換性の問題っぽかったので，Claudeの指示に従ってkbfira_setup/mysql/dataを別のフォルダに退避した後，down -> build -> up -> 初期データのセットの順にやり直したら問題なかった．
その後，再度down -> build -> upをしてみたが初期データのセットはせずともサインインできたので，バージョンが揃っていればdataフォルダは毎回退避しなくてもいいのかもしれない．
